<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Exceptions</title>
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="css/reveal.css" rel="stylesheet" />
    <link href="css/simple.css" rel="stylesheet" />
    <link href="css/googlecode.css" rel="stylesheet" />
  </head>
  <body>
    <div class="reveal">
      <div class="slides"><section class="center" data-background="#000">
  <h1 class="white">
    Exceptions
  </h1>
</section>
<section class="center">
  <p>
    I don't have anything administrative to say, but I hate leaving this slide blank
  </p>
</section>
<section class="center" data-background="#000">
  <p class="white">
    Superstitions <span class="fragment">== Best Practices</span>
  </p>
</section>
<section class="center">
  <img class="inline" src="img/troll.png" />
</section>
<section class="center" data-background="#000">
  <SOLID></SOLID>
</section>
<section>
  <h2>
    SOLID
  </h2>
  <ul>
    <li>
      Single responsibility principle
    </li>
    <li>
      Open/closed principle
    </li>
    <li>
      Liskov substitution principle
    </li>
    <li>
      Interface segregation principle
    </li>
    <li>
      Dependency inversion principle
    </li>
  </ul>
</section>
<section class="center" data-background="#000">
  <h2 class="white">
    Questions
  </h2>
</section>
<section class="center">
  <p>
    What does Object#is_a? do?
  </p>
</section>
<section class="center">
  <p>
    What does Object#kind_of? do?
  </p>
</section>
<section class="center">
  <p>
    What does Object#instance_of? do?
  </p>
</section>
<section class="center">
  <p>
    What is a method alias?
  </p>
</section>
<section class="center">
  <p>
    What is the difference between alias and alias_method?
  </p>
</section>
<section class="center">
  <p>
    What does Object#send does?
  </p>
</section>
<section class="center">
  <p>
    What does Object#public_send does?
  </p>
</section>
<section class="center" data-background="#87cefa">
  <p class="white">
    Why is the sky blue?
  </p>
</section>
<section class="center">
  <p>
    What should happen if I read from a file that doesn't exist?
  </p>
</section>
<section class="center">
  <p>
    What should happen if I write to the disk and the disk is full?
  </p>
</section>
<section class="center">
  <p>
    What should happen if I open a website that doesn't exist?
  </p>
</section>
<section class="center">
  <p>
    What should happen if I access an element that doesn't exist in a Hash?
  </p>
</section>
<section class="center">
  <p>
    What should happen if I delete by zero?
  </p>
</section>
<section class="center">
  <p>
    What should happen if I access a method that doesn't exist?
  </p>
</section>
<section class="center" data-background="#000">
  <h2 class="white">
    Errors
  </h2>
</section>
<section class="center">
  <p>
    Something that shouldn't happen
  </p>
</section>
<section class="center">
  <p>
    But always does
  </p>
</section>
<section class="center">
  <img class="inline" src="img/troll.png" />
</section>
<section class="center" data-background="#000">
  <h2 class="white">
    Exceptions
  </h2>
</section>
<section>
  <h2>
    Exception
  </h2>
  <p>
    Errors in Ruby are represented by exceptions
  </p>
</section>
<section>
  <h2>
    Exception
  </h2>
  <p>
    Is an object of a type Exception
  </p>
</section>
<section>
  <h2>
    Exception
  </h2>
  <p>
    They stop the current execution flow, unless they are handled
  </p>
</section>
<section>
  <h2>
    begin
  </h2>
  <p>
    We handle exceptions in begin/rescue/else/ensure blocks
  </p>
  <pre><code class="ruby">f = File.open("testfile")
begin
  # .. process
rescue
  # .. handle error
else
  puts "Congratulations-- no errors!"
ensure
  f.close unless f.nil?
end </code></pre>
</section>
<section data-background="#000">
  <pre class="white">Exception
  NoMemoryError
  ScriptError
    LoadError
    NotImplementedError
    SyntaxError
  SecurityError
  SignalException
    Interrupt
  StandardError -- default for rescue
  SystemExit
  SystemStackError
  fatal â€“- impossible to rescue </pre>
</section>
<section data-background="#000">
  <pre class="white">StandardError -- default for rescue
  ArgumentError
  EncodingError
  FiberError
  IOError
    EOFError
  IndexError
    KeyError
    StopIteration
  LocalJumpError
  NameError
    NoMethodError
  RangeError
    FloatDomainError
  RegexpError
  RuntimeError -- default for raise
  SystemCallError
    Errno::*
  ThreadError
  TypeError
  ZeroDivisionError </pre>
</section>
<section>
  <h2>
    retry
  </h2>
  <p>
    We can play the block all over again
  </p>
  <pre><code class="ruby">@esmtp = true
begin
  # First try an extended login. If it fails because the
  # server doesn't support it, fall back to a normal login
  if @esmtp
    @command.ehlo(helodom)
  else
    @command.helo(helodom)
  end
rescue ProtocolError
  if @esmtp
    @esmtp = false
    retry
  else
    raise
  end
end </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    You can raise exceptions in your code with Kernel#raise
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    First form reraises the current exception
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    Raises RuntimeError if there is no current exception
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    Used in exception handlers that need to intercept an exception before passing it on
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    Second form creates a new RuntimeError exception, setting its message to the given string
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    The third form uses the first argument to create an exception and then sets the associated message to the second argument and the stack trace to the third argument
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    Technically, this argument can be any object that responds to the message exception by returning an object such that object.kind_of?(Exception) is true
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <h2>
    Kernel#raise
  </h2>
  <p>
    The stack trace is normally produced using the Kernel#caller method
  </p>
  <pre><code class="ruby">raise
raise "bad mp3 encoding"
raise InterfaceException, "Keyboard failure", caller </code></pre>
</section>
<section>
  <pre><code class="ruby" contenteditable="">raise

raise "Missing name" if name.nil?

if i >= myNames.size
  raise IndexError, "#\{i} >= size (#\{myNames.size})"
end

raise ArgumentError, "Name too big", caller </code></pre>
</section>
<section class="center" data-background="#000">
  <h2 class="white">
    Quirks
  </h2>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    The exception matching rescues the first #is_a?
  </p>
  <pre><code class="ruby" contenteditable="">begin
  [].fetch(42)
rescue StandardError
  puts "A STANDARD ERROR"
rescue IndexError
  puts "PLEASE DON'T HANDLE EXCEPTIONS LIKE THAT"
end </code></pre>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    The exception matching rescues the first #is_a?
  </p>
  <pre><code class="ruby" contenteditable="">begin
  {}.fetch(42)
rescue IndexError
  puts "AN INDEX ERROR"
rescue KeyError
  puts "PLEASE DON'T HANDLE EXCEPTIONS LIKE THAT"
end </code></pre>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    The method body is implicit begin block
  </p>
  <pre><code class="ruby" contenteditable="">def read_file(path)
  file = File.open(path.to_s)
rescue
  # Errors, handle them all!
else
  # No errors, yay!
ensure
  file.close if file
end </code></pre>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    begin can be used without rescue
  </p>
  <pre><code class="ruby" contenteditable="">class Something
  def valueccount_no ''
    @value ||= begin
                 value = method_calculation
                 value.transform!
                 value.transform_even_more!
                 value
               end
  end
end </code></pre>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    rescue has an expression modifier form
  </p>
  <pre><code class="ruby" contenteditable="">class Something
  def value
    [].fetch(42) rescue 42
  end
end </code></pre>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    Don't use it!
  </p>
  <pre><code class="ruby" contenteditable="">This is valid Ruby rescue :lol </code></pre>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    Don't use it!
  </p>
  <pre><code class="ruby" contenteditable="">You can write a whole fucking sentence rescue :lol </code></pre>
</section>
<section>
  <h2>
    Quirks
  </h2>
  <p>
    Don't use it!
  </p>
  <pre><code class="ruby" contenteditable="">You can write a whole fucking sentence rescue nil </code></pre>
</section>
<section class="center" data-background="#000">
  <h2 class="white">
    Control Flow
  </h2>
</section>
<section class="center">
  <p>
    While the exception mechanism of raise and rescue is great for abandoning execution
  </p>
</section>
<section class="center">
  <p>
    Sometimes its nice to be able to jump out of some deeply nested construct during normal processing
  </p>
</section>
<section class="center">
  <p>
    This is where catch and throw come in handy
  </p>
</section>
<section class="center">
  <pre><code class="ruby" contenteditable="true">catch :done do
  while gets
    throw :done unless fields = split(/\t/)
    songs.add Song.new(*fields)
  end
  songs.play
end </code></pre>
</section>
<section>
  <h2>
    Kernel#catch
  </h2>
  <p>
    Defines a block that is labeled with the given name (Symbol or a String)
  </p>
  <pre><code class="ruby" contenteditable="true">catch :done do
  while gets
    throw :done unless fields = split(/\t/)
    songs.add Song.new(*fields)
  end
  songs.play
end </code></pre>
</section>
<section>
  <h2>
    Kernel#catch
  </h2>
  <p>
    The block is executed normally until a throw is encountered
  </p>
  <pre><code class="ruby" contenteditable="true">catch :done do
  while gets
    throw :done unless fields = split(/\t/)
    songs.add Song.new(*fields)
  end
  songs.play
end </code></pre>
</section>
<section>
  <h2>
    Kernel#throw
  </h2>
  <p>
    When Ruby encounters a throw, it zips back up the call stack looking for a catch block with a matching symbol
  </p>
  <pre><code class="ruby" contenteditable="true">catch :done do
  while gets
    throw :done unless fields = split(/\t/)
    songs.add Song.new(*fields)
  end
  songs.play
end </code></pre>
</section>
<section>
  <h2>
    Kernel#throw
  </h2>
  <p>
    When it finds it, Ruby unwinds the stack to that point and terminates the block
  </p>
  <pre><code class="ruby" contenteditable="true">catch :done do
  while gets
    throw :done unless fields = split(/\t/)
    songs.add Song.new(*fields)
  end
  songs.play
end </code></pre>
</section>
<section>
  <h2>
    Kernel#throw
  </h2>
  <p>
    If the throw is called with the optional second parameter, that value is returned as the value of the catch
  </p>
  <pre><code class="ruby" contenteditable="true">catch :done do
  while gets
    throw :done unless fields = split(/\t/)
    songs.add Song.new(*fields)
  end
  songs.play
end </code></pre>
</section>
<section class="center" data-background="#000">
  <blockquoute class="white">Exceptions are exceptional</blockquoute>
  <p class="white">
    Dimitar Dimitrov
  </p>
</section>
      </div>
    </div>
    <script src="js/head.min.js"></script>
    <script src="js/reveal.js"></script>
    <script type="text/javascript">
      Reveal.initialize({
        width:  '100%',
        height: '100%',
        margin: 0.05,
        controls: false,
        progress: false,
        history: true,
        center: false,
        rollingLinks: true,
        transition: 'none',
        backgroundTransition: 'none',
        dependencies: [
          {
            src: 'js/highlight.js',
            async: true,
            callback: function() {
              hljs.configure({ languages: ['ruby'] });
              hljs.initHighlightingOnLoad();
            }
          }
        ]
      });
    </script>
  </body>
</html>